import { chromium, devices } from 'playwright';
const b = await chromium.launch(); const c = await b.newContext({ ...devices['iPhone 13'] });
await c.route('**/config.js', (r) => r.fulfill({ contentType: 'application/javascript', body: 'window.RETO29_CONFIG = { MODO: "demo" };' }));
const p = await c.newPage();
await p.goto('http://localhost:5173'); await p.fill('input[name=codigo]', 'demo'); await p.click('button.cta');
await p.locator('.nombre', { hasText: /^Ancho$/ }).click(); await p.waitForSelector('.prog');
await p.goto('http://localhost:5173/nuevo'); await p.waitForSelector('.chips');
const b64 = await p.evaluate(() => { const c = document.createElement('canvas'); c.width = 1200; c.height = 900; const g = c.getContext('2d'); g.fillStyle = '#b87'; g.fillRect(0, 0, 1200, 900); return c.toDataURL('image/jpeg', 0.9).split(',')[1]; });
await p.locator('input[type=file]:not([capture])').first().setInputFiles({ name: 'f.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(b64, 'base64') });
await p.waitForSelector('.foto-prev img');
for (const n of ['Serginho', 'Julia de la T.', 'Roti']) await p.click(`.chips .chip[data-nombre="${n}"]`);
await p.screenshot({ path: '/tmp/nuevo.png', fullPage: true }); await b.close();
